name: income_life
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  diox: ^5.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_state_notifier: ^0.7.1
  fluttertoast: ^8.1.2
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_mobile_ads: ^1.3.0
  gsheets: ^0.4.2
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0
  intl: ^0.17.0
  json_serializable: ^6.5.4
  pie_chart: ^5.3.2
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  simple_logger: ^1.9.0+1
  state_notifier: ^0.7.2+1
  syncfusion_flutter_gauges: ^20.4.51
  webview_flutter: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  pedantic_mono: ^1.20.0

flutter:
  uses-material-design: true
  generate: true

import_path_converter:
  relative: true
flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/income_life_icon.png"
